name: "Blog of Fakecola"
description: "Web Engineering Blog by Fakecola"

url: "http://www.freeclan.net/fakecola"
loadingImg: "http://www.freeclan.net/fakecola/img/loading.gif"
filePath: "http://www.freeclan.net/fakecola/img"

timezone: Asia/Beijing

paginate: 16
paginate_path: "/page:num"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge

permalink: pretty

gems:
- jekyll-paginate
exclude: ["node_modules"]
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
